create database DBNVConsulting;
use DBNVConsulting;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALUMNO_CURSOS](
	[ID_ALUMNO_CURSOS] [int] IDENTITY(1,1) NOT NULL,
	[ID_CURSOS] [int] NULL,
	[ID_ALUMNO] [int] NULL,
 CONSTRAINT [PK_ALUMNO_CURSOS] PRIMARY KEY CLUSTERED 
(
	[ID_ALUMNO_CURSOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALUMNOS](
	[ID_ALUMNO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRES] [Varchar](50) NULL,
	[APELLIDOS] [Varchar](50) NULL,
	[DNI] [char](8) NULL,
	[CORREO] [varchar](50) NULL,
	[TELEFONO] [CHAR](9) NULL,
	[DIRECCION] [varchar](50) NULL,
 CONSTRAINT [PK_ALUMNOS] PRIMARY KEY CLUSTERED 
(
	[ID_ALUMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARGO](
	[ID_CARGO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NULL,
 CONSTRAINT [PK_CARGO] PRIMARY KEY CLUSTERED 
(
	[ID_CARGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CURSOS](
	[ID_CURSOS] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NULL,
	[NRO_HORAS] [INT] NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FIN] [datetime] NULL,
	[PRECIO_CURSO] [DECIMAL](10,2) NULL,
	[ID_EMPLEADOS] [INT] NULL,
 CONSTRAINT [PK_CURSOS] PRIMARY KEY CLUSTERED 
(
	[ID_CURSOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADOS](
	[ID_EMPLEADOS] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRES] [Varchar](50) NULL,
	[APELLIDOS] [Varchar](50) NULL,
	[DNI] [char](8) NULL,
	[CORREO] [varchar](50) NULL,
	[TELEFONO] [CHAR](9) NULL,
	[DIRECCION] [varchar](50) NULL,
	[ID_CARGO] [INT] NULL,
 CONSTRAINT [PK_EMPLEADOS] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAGO](
	[ID_PAGO] [int] IDENTITY(1,1) NOT NULL,
	[FORMA_PAGO] [Varchar](50) NULL,
	[ENTIDAD_FINANCIERA] [Varchar](50) NULL,
	[FECHA_HORA] [DATETIME] NULL,
	[ESTADO] [varchar](50) NULL,
	[OBSERVACION] [VARCHAR](50) NULL,
	[ID_CURSOS] [INT] NULL,
	[ID_ALUMNO] [INT] NULL,
 CONSTRAINT [PK_PAGO] PRIMARY KEY CLUSTERED 
(
	[ID_PAGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROL](
	[ID_ROL] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [Varchar](50) NULL,
	[ESTADO] [Varchar](50) NULL,
	[ID_USUARIOS] [INT] NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[ID_ROL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[ID_USUARIOS] [int] IDENTITY(1,1) NOT NULL,
	[OBSERVACION] [Varchar](50) NULL,
	[ID_EMPLEADOS] [INT] NULL,
	[ID_ALUMNO] [INT] NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ALUMNO_CURSOS]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_CURSOS_CURSO] FOREIGN KEY([ID_CURSOS])
REFERENCES [dbo].[CURSOS] ([ID_CURSOS])
GO
ALTER TABLE [dbo].[ALUMNO_CURSOS] CHECK CONSTRAINT [FK_ALUMNO_CURSOS_CURSO]
GO

ALTER TABLE [dbo].[ALUMNO_CURSOS]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_CURSOS_ALUMNO] FOREIGN KEY([ID_ALUMNO])
REFERENCES [dbo].[ALUMNOS] ([ID_ALUMNO])
GO
ALTER TABLE [dbo].[ALUMNO_CURSOS] CHECK CONSTRAINT [FK_ALUMNO_CURSOS_ALUMNO]
GO

ALTER TABLE [dbo].[CURSOS]  WITH CHECK ADD  CONSTRAINT [FK_CURSOS_EMPLEADOS] FOREIGN KEY([ID_EMPLEADOS])
REFERENCES [dbo].[EMPLEADOS] ([ID_EMPLEADOS])
GO
ALTER TABLE [dbo].[CURSOS] CHECK CONSTRAINT [FK_CURSOS_EMPLEADOS]
GO

ALTER TABLE [dbo].[EMPLEADOS]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADOS_CARGO] FOREIGN KEY([ID_CARGO])
REFERENCES [dbo].[CARGO] ([ID_CARGO])
GO
ALTER TABLE [dbo].[EMPLEADOS] CHECK CONSTRAINT [FK_EMPLEADOS_CARGO]
GO

ALTER TABLE [dbo].[PAGO]  WITH CHECK ADD  CONSTRAINT [FK_PAGO_CURSOS] FOREIGN KEY([ID_CURSOS])
REFERENCES [dbo].[CURSOS] ([ID_CURSOS])
GO
ALTER TABLE [dbo].[PAGO] CHECK CONSTRAINT [FK_PAGO_CURSOS]
GO

ALTER TABLE [dbo].[PAGO]  WITH CHECK ADD  CONSTRAINT [FK_PAGO_ALUMNO] FOREIGN KEY([ID_ALUMNO])
REFERENCES [dbo].[ALUMNOS] ([ID_ALUMNO])
GO
ALTER TABLE [dbo].[PAGO] CHECK CONSTRAINT [FK_PAGO_ALUMNO]
GO

ALTER TABLE [dbo].[ROL]  WITH CHECK ADD  CONSTRAINT [FK_ROL_USUARIOS] FOREIGN KEY([ID_USUARIOS])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIOS])
GO
ALTER TABLE [dbo].[ROL] CHECK CONSTRAINT [FK_ROL_USUARIOS]
GO

ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOS_EMPLEADOS] FOREIGN KEY([ID_EMPLEADOS])
REFERENCES [dbo].[EMPLEADOS] ([ID_EMPLEADOS])
GO
ALTER TABLE [dbo].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS_EMPLEADOS]
GO

ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOS_ALUMNO] FOREIGN KEY([ID_ALUMNO])
REFERENCES [dbo].[ALUMNOS] ([ID_ALUMNO])
GO
ALTER TABLE [dbo].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS_ALUMNO]
GO





